#!/bin/bash

print_config() {
  echo "import { defineConfig } from 'vite'"
  echo ""
  echo "export default defineConfig({"
  echo "  test: {"
  echo "    environment: 'jsdom',"
  echo "  }"
  echo "})"
}

npm install -SE --force \
  vitest \
  @testing-library/react \
  @testing-library/user-event \
  @testing-library/jest-dom \
  jsdom

print_config >vitest.config.js
