#!/bin/bash

COUNT=$(ip route ls | grep "10.3.0.0" | wc -l)

if [[ "$COUNT" == "0" ]]; then
  echo "You should connect to itcollege network through vpn"
  echo "Check itcollege/openvpn recipe"
else
  echo "Found itcollege network"
  open http://10.3.20.10:8006
fi
