#!/bin/bash

BIN0=$(readlink -f $0)
DIR0=$(dirname $BIN0)
INFO=$DIR0/env.tpl

source $DIR0/../../../bin/fn

main() {
  T=$(mktemp)
  cat $INFO > $T
  nvim $T
  source $T

  if [[ "$URL" != "" && "$ID" != "" && "$TARGET_DIR" != "" && "$TARGET_FILE" != "" ]]; then
    if [ ! -f "$TARGET_FILE" ]; then
      download "$URL"
    fi
    [ ! -d "$TARGET_DIR" ] && mkdir -p "$TARGET_DIR"
    [ -f "$ID.mp3" ] && mv "$ID.mp3" "$TARGET_DIR/${TARGET_FILE}.mp3"
  else
    [[ "$URL" == "" ]] && info "You did not specify url"
    [[ "$ID" == "" ]] && info "You did not specify ID"
    [[ "$TARGET_DIR" ]] && info "You did not specify DIR"
    [[ "$TARGET_FILE" ]] && info "You did not specify FILE"
    warn "Please try again"
  fi
}

main
